name: Build Updatecli

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: dolldot/webest:${{ github.sha }}

  commit-change:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - build
    steps:
      - name: Checkout Target Repository
        uses: actions/checkout@v4
        with:
          repository: dolldot/manifests
          path: manifests
          token: ${{ secrets.GH_TOKEN }}
      - name: Set variables
        run: |
          commit_hash=${{ github.sha }}
          IMAGE_TAG=${commit_hash::7}
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
      - name: Update deployment manifest
        working-directory: manifests
        run: |
          manifests='["tenants/webest/values.yaml","tenants/echo-headers/values.yaml"]'
          echo "$manifests" | jq -r '.[]' | while read -r manifest; do
            sed -i "s/tag: .*/tag: \"${IMAGE_TAG}\"/" $manifest
          done
      - name: Commit the changes
        working-directory: manifests
        run: |
          git add .
          git config user.name dotbot
          git config user.email dotbot@dummy.com
          git commit -m "Update image to ${IMAGE_TAG}"
          git push
