name: Build using yaml-update-action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: dolldot/webest:${{ github.sha }}

  create-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - build
    steps:
      - name: Checkout Target Repository
        uses: actions/checkout@v4
        with:
          repository: dolldot/manifests
          path: manifests
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'tenants/webest/values.yaml'
          propertyPath: 'image.tag'
          value: ${{ github.sha }}
          repository: dolldot/manifests
          masterBranchName: main
          branch: deployment/${{ github.sha }}
          targetBranch: main
          createPR: true
          message: 'Update Image Tag to ${{ github.sha }}'
          token: ${{ secrets.GH_TOKEN }}
          workDir: manifests
