name: Build PR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: dolldot/webest:${{ github.sha }}

  create-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - build
    steps:
      - name: Checkout Target Repository
        uses: actions/checkout@v4
        with:
          repository: dolldot/manifests
          path: manifests
          token: ${{ secrets.GH_TOKEN }}
      - name: Set variables
        run: |
          commit_hash=${{ github.sha }}
          IMAGE_TAG=${commit_hash::7}
          MANIFEST_PATH=tenants/webest
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
          echo "MANIFEST_PATH=${MANIFEST_PATH}" >> $GITHUB_ENV
      - name: Create Update Branch
        working-directory: manifests
        run: |
          git config user.name dotbot
          git config user.email dotbot@dummy.com
          git checkout -b bot/update-manifest-${{ env.IMAGE_TAG }}
      - name: Update values.yaml
        working-directory: manifests
        run: |
          MANIFEST_PATH=${{ env.MANIFEST_PATH }}
          sed -i "s/tag: .*/tag: ${IMAGE_TAG}/" ${MANIFEST_PATH}/values.yaml
          git add .
          git commit -m "Update manifest ${MANIFEST_PATH}"
          git push origin bot/update-manifest-${{ env.IMAGE_TAG }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: "Update manifest ${{ env.MANIFEST_PATH }}"
          branch: bot/update-manifest-${{ env.IMAGE_TAG }}
          title: "Update manifest ${{ env.MANIFEST_PATH }}"
          body: "This PR updates the manifest with the new image tag: ${{ env.IMAGE_TAG }}"
          base: main
          path: manifests
